### ISSUE TITLE
Replays can't save to folder unless one of the two upload checkboxes are checked

### ISSUE THREAD

**Issue by CinderBlocc** [bakkesmodorg/AutoReplayUploader#16]
Inside `OnGameComplete` the first if statement only checks if the upload cvars are enabled. That bypasses the `ExportReplay` call later in that function, even though the `CVAR_REPLAY_EXPORT` cvar is enabled. Below is the current code:
```
if (!*uploadToCalculated && !*uploadToBallchasing) // Bail if we aren't uploading replays
{
	return; //Not uploading replays
}
```
and I would recommend changing it to this:
```
if (!*uploadToCalculated && !*uploadToBallchasing && !*saveReplay) // Bail if we aren't uploading or saving replays
{
	return; //Not uploading or saving replays
}
```

**Comment by Bakkes** [comment]
Thank you!
